### ISSUE TITLE
Update to ASB .netstd 1.0

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet-plugins#20]
With ASB .netstd client published ( 🎉 🎂 ) this repo should be updated as well.

**Comment by SeanFeldman** [comment]
@vinaysurya a bit early to close it - nuget package is not on NuGet.

**Comment by vinaysurya** [comment]
Ok, I didn't think this issue was tracking the release of the nuget. Let me check if we have any other planned fixes to be done.. If not we can work on releasing the nuget with the new client reference.

**Comment by SeanFeldman** [comment]
👍 
Being a downstream with a dependency on ASB .NETstd, might be good to keep in mind to to associate nuget package release with any significant changes in upstream (such as in this case). At least until there's some sort of automation in place.

**Comment by SeanFeldman** [comment]
@vinaysurya  GA-ed version is still [missing from NuGet](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus.MessageIdPlugin/).
