### ISSUE TITLE
Releasing stable version

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet-plugins#24]
The plugin has not been published for any of the stable versions.
As of now, it's targetting `Microsoft.Azure.ServiceBus 0.0.6-preview`.

PR #23 was merged a few weeks ago into `dev` w/o being released.

cc @ChristianWolf42

**Comment by ChristianWolf42** [comment]
We will look into this before xmas but are a bit tied up right now so it may take 2-3 weeks.

**Comment by SeanFeldman** [comment]
If I could, I'd do it. But I can't 🙂

**Comment by tomkerkhove** [comment]
What's the status here?

**Comment by ChristianWolf42** [comment]
@tomkerkhove and @SeanFeldman, We uploaded the package right now. Should be done in 1h (Some nuget internal processes)
