### ISSUE TITLE
Update Readme.md to indicate what this repo is

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet-plugins#4]
Document in [readme.md](https://github.com/Azure/azure-service-bus-dotnet-plugins/blob/dev/README.md) the following:
- What plugins will be found in this repo
- What plugins are considered for this repo vs what's not
- General rules about plugins (expectations, criteria for acceptance, etc)

**Comment by nemakam** [comment]
#16 takes care of this.
