### ISSUE TITLE
What access level should ServiceBusPlugin BeforeMessageSend and AfterMessageReceive methods be

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet-plugins#6]
Currently methods are public.
@nemakam [suggested](https://github.com/Azure/azure-service-bus-dotnet-plugins/pull/5/files/98df4bc613bf60de75024bcd35ccfefe24e2b0ea#r120520589) to make them protected. 

Should those methods be protected?

**Comment by nemakam** [comment]
Closing this issue. Since `MessageReceiver` and `MessageSender` need to call these methods, it has to be public. Hiding these plugin methods from the user should be taken care by other means.
