### ISSUE TITLE
Pre-releasing

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet-plugins#8]
There are 2 functional plugins that would be nice to test drive using nuget package (issue #3).

@ShubhaVijayasarathy @JustinConway @banisadr who's going to drive it? 

![image](https://user-images.githubusercontent.com/1309622/27115231-8863a072-5086-11e7-9ed2-b94e1dffe5dc.png)

**Comment by clemensv** [comment]
The team is doing lots of things, visible and invisible, especially at this time of the year. Proposals for activities to take on are welcome, but trying to dispatch work to particular people is inappropriate, Sean.

**Comment by SeanFeldman** [comment]
As an external contributor I absolutely agree with your statement about visibility.
I'm taking on things as much as I can. I'm also flying blind w/o visibility. The intent was not to dispatch work to anyone (sorry if it came that way), but to get an idea who's leading/providing feedback on the issues. 

#3 has been raised and there was a complete silence. I was hoping to get some attention to understand what the plan is. Ideally, there would be milestones, but this is a real world. No need to be harsh.

**Comment by clemensv** [comment]
Opening an issue to call attention to a different issue and calling out a set of people for "who is going to drive it" is kinda harsh all by itself.
